### ISSUE TITLE
Apple build doesn't work under rust 1.83

### ISSUE THREAD

**Issue by pankcuf** [dashpay/bls-signatures#108]
There are 2 problems:
- 1.3.3 doesn't work under rust toolchain 1.83

> Undefined symbols for architecture arm64:
            "___chkstk_darwin", referenced from:
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ___gmpn_mul in libbls_dash_sys-d3fd00d0665689ca.rlib[320](lt82-mul.o)
                ...
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
- 1.3.5 doesn't work at all (1.81 / 1.83)

**Comment by PastaPastaPasta** [comment]
did 1.3.3 work with rust 1.81?

**Comment by knst** [comment]
> 1.3.5 doesn't work at all (1.81 / 1.83)

How exactly doesn't work it at all?

Does it compile? Linked? Runs? Crashes? Produces wrong libraries? Can't open project?

**Comment by pankcuf** [comment]
@PastaPastaPasta yes
@knst same as in 1.3.3 under 1.83 + seems like gmp doesn't work in 1.3.5 

> configure: error: could not find a working compiler, see config.log for details
config.log:

> This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU MP configure 6.3.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang CFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  CPPFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  LDFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  --host=aarch64-apple-darwin --prefix=/Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/gmplib-- --disable-shared --enable-static --disable-assembly -v

## --------- ##
## Platform. ##
## --------- ##

hostname = Vladimirs-MacBook-Pro.local
uname -m = arm64
uname -r = 23.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Kernel configured for up to 12 processors.
12 processors are physically available.
12 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11
Primary memory available: 32.00 gigabytes
Default processor set: 739 tasks, 4318 threads, 12 processors
Load average: 20.01, Mach factor: 0.90
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin
PATH: /Applications/Xcode.app/Contents/Developer/usr/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /opt/homebrew/bin
"./build/contrib/gmp/config.log" 363L, 14257B
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU MP configure 6.3.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang CFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  CPPFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  LDFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  --host=aarch64-apple-darwin --prefix=/Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/gmplib-- --disable-shared --enable-static --disable-assembly -v

## --------- ##
## Platform. ##
## --------- ##

hostname = Vladimirs-MacBook-Pro.local
uname -m = arm64
uname -r = 23.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Kernel configured for up to 12 processors.
12 processors are physically available.
12 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11
Primary memory available: 32.00 gigabytes
Default processor set: 739 tasks, 4318 threads, 12 processors
Load average: 20.01, Mach factor: 0.90
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin
PATH: /Applications/Xcode.app/Contents/Developer/usr/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /opt/homebrew/bin
"./build/contrib/gmp/config.log" 363L, 14257B
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU MP configure 6.3.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was


## --------- ##
## Platform. ##
## --------- ##

hostname = Vladimirs-MacBook-Pro.local
uname -m = arm64
uname -r = 23.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

         Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Kernel configured for up to 12 processors.
12 processors are physically available.
12 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11
Primary memory available: 32.00 gigabytes
Default processor set: 739 tasks, 4318 threads, 12 processors
Load average: 20.01, Mach factor: 0.90
/bin/machine           = unknown
PATH: /Applications/Xcode.app/Contents/Developer/usr/bin

## ----------- ##
## Core tests. ##
## ----------- ##

configure:3056: checking build system type
configure:3070: result: aarch64-apple-darwin23.5.0
configure:3090: checking host system type
configure:3103: result: aarch64-apple-darwin
configure:3140: checking for a BSD-compatible install
configure:3208: result: /usr/bin/install -c
configure:3373: checking for strip
configure:3501: result: no
configure:3471: checking for nawk
configure:3501: result: no
configure:3471: checking for awk
configure:3487: found /usr/bin/awk
configure:3498: result: awk
configure:3509: checking whether make sets $(MAKE)
configure:3531: result: yes
configure:3560: checking whether make supports nested variables
configure:3577: result: yes
configure:3706: checking whether to enable maintainer-specific portions of Makefiles
configure:3715: result: no
User:
ABI=
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
MPN_PATH=
GMP:
configure:5889: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c conftest.c >&5
configure:5897: result: yes
configure:5911: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang 2>&1 | grep xlc >/dev/null
configure:5914: $? = 1
Test compile:
configure:5985: $? = 1
failed program was:

int main () { return 0; }
configure:7072: result: no
configure:5889: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c conftest.c >&5
configure:5892: $? = 0
configure:5895: checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang is gcc
configure:5897: result: yes
configure:5911: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang 2>&1 | grep xlc >/dev/null
configure:5914: $? = 1
Test compile:
configure:5985: $? = 1
failed program was:

int main () { return 0; }
configure:7072: result: no
configure:7310: error: could not find a working compiler, see config.log for details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=aarch64-apple-darwin23.5.0
ac_cv_env_ABI_set=
ac_cv_env_ABI_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_FOR_BUILD_set=
ac_cv_env_CC_FOR_BUILD_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
ac_cv_env_CFLAGS_set=set
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPP_FOR_BUILD_set=
ac_cv_env_CPP_FOR_BUILD_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_M4_set=
ac_cv_env_M4_value=
ac_cv_env_YACC_set=
ac_cv_env_YACC_value=
ac_cv_env_YFLAGS_set=
ac_cv_env_YFLAGS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=aarch64-apple-darwin
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=aarch64-apple-darwin
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/opt/homebrew/bin/gmkdir
ac_cv_prog_AWK=awk
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
ABI=''
ACLOCAL='${SHELL} /Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/contrib/gmp/missing aclocal-1.15'
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AS=''
ASMFLAGS=''
AUTOCONF='${SHELL} /Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/contrib/gmp/missing autoconf'
AUTOHEADER='${SHELL} /Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/contrib/gmp/missing autoheader'
AUTOMAKE='${SHELL} /Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/contrib/gmp/missing automake-1.15'
AWK='awk'
CALLING_CONVENTIONS_OBJS='arm32call.lo arm32check.lo'
CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang'
CCAS=''
CC_FOR_BUILD=''
CPP=''
CPP_FOR_BUILD=''
CXX=''
CXXCPP=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFN_LONG_LONG_LIMB=''
DEFS=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
ENABLE_STATIC_FALSE=''
ENABLE_STATIC_TRUE=''
EXEEXT=''
EXEEXT_FOR_BUILD=''
FGREP=''
GMP_LDFLAGS=''
GMP_LIMB_BITS=''
GMP_NAIL_BITS='0'
GREP=''
HAVE_CLOCK_01=''
HAVE_CPUTIME_01=''
HAVE_GETRUSAGE_01=''
HAVE_GETTIMEOFDAY_01=''
HAVE_HOST_CPU_FAMILY_power='0'
HAVE_HOST_CPU_FAMILY_powerpc='0'
HAVE_SIGACTION_01=''
HAVE_SIGALTSTACK_01=''
HAVE_SIGSTACK_01=''
HAVE_STACK_T_01=''
HAVE_SYS_RESOURCE_H_01=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LEX=''
LEXLIB=''
LEX_OUTPUT_ROOT=''
LIBCURSES=''
LIBGMPXX_LDFLAGS=''
LIBGMP_DLL=''
LIBGMP_LDFLAGS=''
LIBM=''
LIBM_FOR_BUILD=''
LIBOBJS=''
LIBREADLINE=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
M4=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/contrib/gmp/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/opt/homebrew/bin/gmkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='gmp'
PACKAGE_BUGREPORT='gmp-bugs@gmplib.org (see https://gmplib.org/manual/Reporting-Bugs.html)'
PACKAGE_NAME='GNU MP'
PACKAGE_STRING='GNU MP 6.3.0'
PACKAGE_TARNAME='gmp'
PACKAGE_URL='http://www.gnu.org/software/gmp/'
PACKAGE_VERSION='6.3.0'
PATH_SEPARATOR=':'
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
SPEED_CYCLECOUNTER_OBJ=''
STRIP='strip'
TAL_OBJECT=''
TUNE_LIBS=''
TUNE_SQR_OBJ=''
U_FOR_BUILD=''
VERSION='6.3.0'
WANT_CXX_FALSE=''
WANT_CXX_TRUE=''
WITH_READLINE_01=''
YACC=''
YFLAGS=''
ac_ct_AR=''
ac_ct_CC=''
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU MP configure 6.3.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang CFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  CPPFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  LDFLAGS=-Wno-unused-value -fembed-bitcode -arch  --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  --host=aarch64-apple-darwin --prefix=/Users/vladimirpirogov/Documents/work/dash/dashpay-bls-signatures/build/gmplib-- --disable-shared --enable-static --disable-assembly -v

## --------- ##
## Platform. ##
## --------- ##

hostname = Vladimirs-MacBook-Pro.local
uname -m = arm64
uname -r = 23.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Kernel configured for up to 12 processors.
12 processors are physically available.
12 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11
Primary memory available: 32.00 gigabytes
Default processor set: 739 tasks, 4318 threads, 12 processors
Load average: 20.01, Mach factor: 0.90
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin
PATH: /Applications/Xcode.app/Contents/Developer/usr/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /opt/homebrew/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:3056: checking build system type
configure:3070: result: aarch64-apple-darwin23.5.0
configure:3090: checking host system type
configure:3103: result: aarch64-apple-darwin
configure:3140: checking for a BSD-compatible install
configure:3208: result: /usr/bin/install -c
configure:3219: checking whether build environment is sane

**Comment by PastaPastaPasta** [comment]
how are you compiling? what commands are you running?  What is this big text wall from?

**Comment by pankcuf** [comment]
1. text wall is from "./build/contrib/gmp/config.log"
2. compilation via apple.rust.deps.sh

**Comment by PastaPastaPasta** [comment]
Okay, not really sure how to help?

apple.rust.deps.sh is predominately owned by / was introduced by you, and has no CI on it.  

apple.rust.deps.sh includes:
```
          -I"../gmplib-${PFX}/include" \
```
have you checked that gmp actually exists here?

**Comment by pankcuf** [comment]
No, gmplib- folder doesn't exist. Instead there are empty folder "gmplib--", I mean It was introduced by me, then @knst and @ogabrielides elaborate through this and made neccessary changes in 1.3.3. And it was working fine. Then smth had broken after 1.3.3. So as I said – there 2 problems: rust 1.83 and changes after 1.3.3

**Comment by PastaPastaPasta** [comment]
Well, the last change to apple.rust.deps.sh was last changed in https://github.com/dashpay/bls-signatures/commit/eda5d6a4028cacd25bc9556d1204470ecd8eac76, which was in 1.3.3, so since 1.3.3 in that file no changes have been make.

Since 1.3.3, only 19 commits have been made, touching 7 files, none of which seem would impact you. https://github.com/dashpay/bls-signatures/compare/1.3.3...dashpay:bls-signatures:main Maybe you can git bisect using rust 1.81 and see what commit causes an issue?

**Comment by pankcuf** [comment]
@PastaPastaPasta eventually I could do that. But maybe let's focus on rust 1.83? I can live with 1.3.3 for now, but rust 1.83 is a requirement for the latest platform release

**Comment by pankcuf** [comment]
ok, part of the problem is clear, I didn't figure out that we moved arch setting outside of the apple.rust.deps.sh... So the remaining problem is 1.83. And I suspect, that it has smth todo with cargo-lipo

**Comment by pankcuf** [comment]
Preliminary, I think I handled 1.83 problem...

**Comment by pankcuf** [comment]
Closing. In general, the fix consists of raising the iOS build version above 13 when building bls for 1.83. In principle, there is no need for edits in the bls repo, I can configure this from the outside.
